[[utf8proc]]
arch = "aarch64"
git-tree-sha1 = "7f712690d928c55cb46ea8a8810c35089409eef5"
os = "macos"

    [[utf8proc.download]]
    sha256 = "a8e1dfee6064f8bf96b951f8ec5b2e1f1654a48f7f3165fd39bb1becf8c20519"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.2+0/utf8proc.v2.11.2.aarch64-apple-darwin.tar.gz"
[[utf8proc]]
arch = "aarch64"
git-tree-sha1 = "8df0164858f149c538ad2c6567843c4a35de5b8b"
libc = "glibc"
os = "linux"

    [[utf8proc.download]]
    sha256 = "059e3729d17bde3acdad5a76ee26b6ded05b509ae429117f4e8590d5f1379554"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.2+0/utf8proc.v2.11.2.aarch64-linux-gnu.tar.gz"
[[utf8proc]]
arch = "aarch64"
git-tree-sha1 = "d34ae76748b47757d4780961a98163182fea2dfd"
libc = "musl"
os = "linux"

    [[utf8proc.download]]
    sha256 = "34822334e98895009cf616b74143a2607dc7c4d2a3cf91bec6356e69c7b7a92a"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.2+0/utf8proc.v2.11.2.aarch64-linux-musl.tar.gz"
[[utf8proc]]
arch = "aarch64"
git-tree-sha1 = "6b74f7f414c19cf5cb13e1e6c599082ee70d2468"
os = "freebsd"

    [[utf8proc.download]]
    sha256 = "288a25e1e8ffac435a856d96827b9c696c5ef09c722a0599cc28d14e5409ce0c"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.2+0/utf8proc.v2.11.2.aarch64-unknown-freebsd.tar.gz"
[[utf8proc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "000dfb08014d5d5fc737b2961ae3c622af606a2e"
libc = "glibc"
os = "linux"

    [[utf8proc.download]]
    sha256 = "877b7c8a4804d37ee5c6779d2700f24ed44bd13f9cf0c7328c13558ef52481db"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.2+0/utf8proc.v2.11.2.armv6l-linux-gnueabihf.tar.gz"
[[utf8proc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c31548f02c0c3593f3a761ab29036fa204add98d"
libc = "musl"
os = "linux"

    [[utf8proc.download]]
    sha256 = "6623fff57146aa73cfe6cb79066c60de77bf72f4f029d8964146c67744613dbb"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.2+0/utf8proc.v2.11.2.armv6l-linux-musleabihf.tar.gz"
[[utf8proc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c6cd8575d0f7313419c59c817fbcab98d70506e3"
libc = "glibc"
os = "linux"

    [[utf8proc.download]]
    sha256 = "00cb9a7f96341ebfdcc95bf71deff4c82ff7e8e624d9d0e030a4eb7ccb589270"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.2+0/utf8proc.v2.11.2.armv7l-linux-gnueabihf.tar.gz"
[[utf8proc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4219ab852f9237745199cc110fc84a8f3fb3c6af"
libc = "musl"
os = "linux"

    [[utf8proc.download]]
    sha256 = "ad51ee0c6194d5ca7b97115452e2da8314cb677c9dbb5e66effd6d25b6c8719d"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.2+0/utf8proc.v2.11.2.armv7l-linux-musleabihf.tar.gz"
[[utf8proc]]
arch = "i686"
git-tree-sha1 = "399e0fefb9fa1d79351e48b2230545a2d63d2a8f"
libc = "glibc"
os = "linux"

    [[utf8proc.download]]
    sha256 = "8fc31a31302ecc8465457732462cadc9185947e4cdaddaef386c1d2bdbff6e51"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.2+0/utf8proc.v2.11.2.i686-linux-gnu.tar.gz"
[[utf8proc]]
arch = "i686"
git-tree-sha1 = "c0f3e6d1269b7cc6e8bacfef7e3b97e3f927f215"
libc = "musl"
os = "linux"

    [[utf8proc.download]]
    sha256 = "9023573805a544b59bcd2db1851c829080d3d56f25bdf17245a0cf9f539978c5"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.2+0/utf8proc.v2.11.2.i686-linux-musl.tar.gz"
[[utf8proc]]
arch = "i686"
git-tree-sha1 = "0bd175f828389d748b5d248327d8631ce06fb458"
os = "windows"

    [[utf8proc.download]]
    sha256 = "c21ede55a8dd63bf8dbeeea2543f39b60963c3326dd9368aade856e7931755ae"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.2+0/utf8proc.v2.11.2.i686-w64-mingw32.tar.gz"
[[utf8proc]]
arch = "powerpc64le"
git-tree-sha1 = "0f481008651d36bb6f1011ed9e46be76ae1801b2"
libc = "glibc"
os = "linux"

    [[utf8proc.download]]
    sha256 = "a0a1c0ef4c47da5d0f9ef61fb68b93af8b83e7abbbaa27a6ebe8f4ee218cadf9"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.2+0/utf8proc.v2.11.2.powerpc64le-linux-gnu.tar.gz"
[[utf8proc]]
arch = "riscv64"
git-tree-sha1 = "f319e4776202ecda71c27d1e87c1ba2effdebc2d"
libc = "glibc"
os = "linux"

    [[utf8proc.download]]
    sha256 = "d373dbf5946a734e1069e08c7a2c4ebd67466252df87a97d54e515b967c473cb"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.2+0/utf8proc.v2.11.2.riscv64-linux-gnu.tar.gz"
[[utf8proc]]
arch = "x86_64"
git-tree-sha1 = "b44e6fbbd2c47ca054721d3f7f61e7c0f1015c39"
os = "macos"

    [[utf8proc.download]]
    sha256 = "d4492d231744ab9bda441cdc2f586e363ed46168919ee79f116b23031275ff06"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.2+0/utf8proc.v2.11.2.x86_64-apple-darwin.tar.gz"
[[utf8proc]]
arch = "x86_64"
git-tree-sha1 = "ca33083f00bcc2dbe1f55b4d811ef02c686b9ca8"
libc = "glibc"
os = "linux"

    [[utf8proc.download]]
    sha256 = "cf5d02f9a682a63212fab30f82fcac9766767d52785c5044e701a2d6fa692acb"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.2+0/utf8proc.v2.11.2.x86_64-linux-gnu.tar.gz"
[[utf8proc]]
arch = "x86_64"
git-tree-sha1 = "85ec764eb4da377cba5e7ae3544754bb98ae225b"
libc = "musl"
os = "linux"

    [[utf8proc.download]]
    sha256 = "8d09df7732a6949c1cf50c7c7c786b0916b2da417bbcbdcb09c1e7e47a26563b"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.2+0/utf8proc.v2.11.2.x86_64-linux-musl.tar.gz"
[[utf8proc]]
arch = "x86_64"
git-tree-sha1 = "a106c8b6f741eea78da269278cfa8278d6ace8c0"
os = "freebsd"

    [[utf8proc.download]]
    sha256 = "47a220aa35effae85f6ce1bacfcf1e1f34c7f168702026c8220b09d6b5ebf384"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.2+0/utf8proc.v2.11.2.x86_64-unknown-freebsd.tar.gz"
[[utf8proc]]
arch = "x86_64"
git-tree-sha1 = "1e88bbb7394ca06603ee7ba693c05f908a6bb858"
os = "windows"

    [[utf8proc.download]]
    sha256 = "05dc81153be401846348a7d236bb0a76d87bd285d85c0849c825056b2a964b0d"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.2+0/utf8proc.v2.11.2.x86_64-w64-mingw32.tar.gz"
