[[utf8proc]]
arch = "aarch64"
git-tree-sha1 = "fe41c2b56d13d33196d360abaced49e2673cf816"
os = "macos"

    [[utf8proc.download]]
    sha256 = "9da9382738dc149b12bcf861c5c1534c1942decc94c674495f53417880af3bf0"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.1+0/utf8proc.v2.11.1.aarch64-apple-darwin.tar.gz"
[[utf8proc]]
arch = "aarch64"
git-tree-sha1 = "1f2c69fbfec16890124491a45331c303a334ff1b"
libc = "glibc"
os = "linux"

    [[utf8proc.download]]
    sha256 = "9d8538f8b6392cfdd34dd51fbc8083d8c47dfeef655ac36c393bfea50431863d"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.1+0/utf8proc.v2.11.1.aarch64-linux-gnu.tar.gz"
[[utf8proc]]
arch = "aarch64"
git-tree-sha1 = "643c4c83f417a0fc5edc1675745315ac8fa0dd26"
libc = "musl"
os = "linux"

    [[utf8proc.download]]
    sha256 = "63569daed7be1c5667c633a05065b6c0d8003185e8af1e716d36b16674ff53cd"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.1+0/utf8proc.v2.11.1.aarch64-linux-musl.tar.gz"
[[utf8proc]]
arch = "aarch64"
git-tree-sha1 = "34c283535d7f0c34ceaac3092dc14f84fc4b221b"
os = "freebsd"

    [[utf8proc.download]]
    sha256 = "0020781bc6d1d0162a741434a7c1f5ad5fe4a93238d2bd93e354d8432f1ee327"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.1+0/utf8proc.v2.11.1.aarch64-unknown-freebsd.tar.gz"
[[utf8proc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b84bbbf23555fe6a5c6e798ed859d55032c0b05c"
libc = "glibc"
os = "linux"

    [[utf8proc.download]]
    sha256 = "daf41d626e340a1382cba4302f6766e600fc25a529589951530d57c7080fdc6e"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.1+0/utf8proc.v2.11.1.armv6l-linux-gnueabihf.tar.gz"
[[utf8proc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "60d85bcc8a037353ea1105c3d9ce0de5fcee7b10"
libc = "musl"
os = "linux"

    [[utf8proc.download]]
    sha256 = "ca0a77f1f27dcc57499dd1dd47f4749615bbff8ae2cf58d307e702f0d2fa18a2"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.1+0/utf8proc.v2.11.1.armv6l-linux-musleabihf.tar.gz"
[[utf8proc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c42e8e27b6822cab594640255bd86b1899d8d87e"
libc = "glibc"
os = "linux"

    [[utf8proc.download]]
    sha256 = "12db844620670988cb52df7826fe08dab161b9f0a93bca3183ed901de1246df4"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.1+0/utf8proc.v2.11.1.armv7l-linux-gnueabihf.tar.gz"
[[utf8proc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9412c73d28e7012587d7ca237e2d3f79d61dbfb7"
libc = "musl"
os = "linux"

    [[utf8proc.download]]
    sha256 = "51e78db4aedda9634d68793b130c93643ee059e6e4ecf5a1136e228b04a7e88f"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.1+0/utf8proc.v2.11.1.armv7l-linux-musleabihf.tar.gz"
[[utf8proc]]
arch = "i686"
git-tree-sha1 = "1f71d356c353288a3c31fa9938b71d6d3f8214fc"
libc = "glibc"
os = "linux"

    [[utf8proc.download]]
    sha256 = "5b668c09b0174d58d23b09fe4c26850fd8633e0d14026025a51111bc7bb7d28d"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.1+0/utf8proc.v2.11.1.i686-linux-gnu.tar.gz"
[[utf8proc]]
arch = "i686"
git-tree-sha1 = "2472ee0e3d8171c1ce7dde8a125d65e277ad6854"
libc = "musl"
os = "linux"

    [[utf8proc.download]]
    sha256 = "392de5af1ad4a548f0d16b48413712183c1c344faa2e49b54e458cc41d438442"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.1+0/utf8proc.v2.11.1.i686-linux-musl.tar.gz"
[[utf8proc]]
arch = "i686"
git-tree-sha1 = "453de1f878e1cf06cf7edd4deb62b1019157baca"
os = "windows"

    [[utf8proc.download]]
    sha256 = "314eb2d8996b4ee34ff06433fb3d2012bf1a6501fedd8cfd9ff69c98449e9abb"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.1+0/utf8proc.v2.11.1.i686-w64-mingw32.tar.gz"
[[utf8proc]]
arch = "powerpc64le"
git-tree-sha1 = "8f5cdfe2189bc89a9d4a5370b747d1a115912759"
libc = "glibc"
os = "linux"

    [[utf8proc.download]]
    sha256 = "fbd5bdcfb5cdd99b34c40fc0e2647607ef2ecbca06437682e5a062681ec2a554"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.1+0/utf8proc.v2.11.1.powerpc64le-linux-gnu.tar.gz"
[[utf8proc]]
arch = "riscv64"
git-tree-sha1 = "d3d9e9187b3ad50329b7a833dff635fd0a246732"
libc = "glibc"
os = "linux"

    [[utf8proc.download]]
    sha256 = "5743f2a5354b65ab6e275d697c2d76385e32221d1f0dbafc3c285c3ea8794002"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.1+0/utf8proc.v2.11.1.riscv64-linux-gnu.tar.gz"
[[utf8proc]]
arch = "x86_64"
git-tree-sha1 = "ca62bfc764837afcd4b497ff42d2f3d456578620"
os = "macos"

    [[utf8proc.download]]
    sha256 = "6192437c5748a2def3bf1aa91cf64ec9709e6a196cd68f9bf08715877203d09d"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.1+0/utf8proc.v2.11.1.x86_64-apple-darwin.tar.gz"
[[utf8proc]]
arch = "x86_64"
git-tree-sha1 = "9da1b27fbd2d6e152d25ddf38111404d61a4f38d"
libc = "glibc"
os = "linux"

    [[utf8proc.download]]
    sha256 = "342ff20305d3de2904ac2d648034b190b1b9813235fe2e2299f4735587864233"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.1+0/utf8proc.v2.11.1.x86_64-linux-gnu.tar.gz"
[[utf8proc]]
arch = "x86_64"
git-tree-sha1 = "256292ff9461821c7e35dd27cac8b45beaab118c"
libc = "musl"
os = "linux"

    [[utf8proc.download]]
    sha256 = "c0ea5f9c07e556e96d4bcaed4a05d39fabee19e75dc9cd1ce8c1aba94c7199ba"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.1+0/utf8proc.v2.11.1.x86_64-linux-musl.tar.gz"
[[utf8proc]]
arch = "x86_64"
git-tree-sha1 = "d7a9a865543e4984952fd1a704c127915e52c71e"
os = "freebsd"

    [[utf8proc.download]]
    sha256 = "1b479bd3364c9c68315902633f22465341089c431e32b55da65e6aa20e6d9785"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.1+0/utf8proc.v2.11.1.x86_64-unknown-freebsd.tar.gz"
[[utf8proc]]
arch = "x86_64"
git-tree-sha1 = "bd9f9bb4df8873446bdb5ad01f561c75e029931e"
os = "windows"

    [[utf8proc.download]]
    sha256 = "538a581b52f3e4f6c30caaec7db6576dc28f8a61032dfa30d753d92020be48a0"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.1+0/utf8proc.v2.11.1.x86_64-w64-mingw32.tar.gz"
