[[utf8proc]]
arch = "aarch64"
git-tree-sha1 = "45ee9b9421a6ca7b2333984d64a41853abe3cc83"
os = "macos"

    [[utf8proc.download]]
    sha256 = "ecc57a7a3cce81516ecf6ebb28cc33f681d329f80dc1b93e4dafabda754e9ba9"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.0+0/utf8proc.v2.11.0.aarch64-apple-darwin.tar.gz"
[[utf8proc]]
arch = "aarch64"
git-tree-sha1 = "295be3f2fc83ec45067ae4308baa51c06c0ffc70"
libc = "glibc"
os = "linux"

    [[utf8proc.download]]
    sha256 = "cbfd620cb63a0f21f43c971ec12cf9e95912220f6f769ee1e32e28030c7f99bf"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.0+0/utf8proc.v2.11.0.aarch64-linux-gnu.tar.gz"
[[utf8proc]]
arch = "aarch64"
git-tree-sha1 = "d1e2e6d9ddb6aa9f5e819c13a172d167761385e3"
libc = "musl"
os = "linux"

    [[utf8proc.download]]
    sha256 = "596ae45cecb2d4ebb6ec4c32c50f1ceec8ea052a99cc0dca7ce1e838b1d3f23c"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.0+0/utf8proc.v2.11.0.aarch64-linux-musl.tar.gz"
[[utf8proc]]
arch = "aarch64"
git-tree-sha1 = "cfd6aedaacff67c6d2aa843689133440eef26eb9"
os = "freebsd"

    [[utf8proc.download]]
    sha256 = "832084ba96028a90d85aedc7ceec9d839385ed8ff2d8b57560e0dd13c056f2a3"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.0+0/utf8proc.v2.11.0.aarch64-unknown-freebsd.tar.gz"
[[utf8proc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3dd27b87995fac9d5fa8c6492df3de0e8e417dc7"
libc = "glibc"
os = "linux"

    [[utf8proc.download]]
    sha256 = "2202285cf342445cd6e71f8af9b99327c6299dca41b6cda2008cf7334359700d"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.0+0/utf8proc.v2.11.0.armv6l-linux-gnueabihf.tar.gz"
[[utf8proc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7ae84fa729785ae52486d1963434cb8fec5b68b0"
libc = "musl"
os = "linux"

    [[utf8proc.download]]
    sha256 = "3c8259fb603ba83af00dca79872c922bee37c2ad4e1f6aface2a646813e651da"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.0+0/utf8proc.v2.11.0.armv6l-linux-musleabihf.tar.gz"
[[utf8proc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2755be40f72685450550f1df0fda3090bee9cf0d"
libc = "glibc"
os = "linux"

    [[utf8proc.download]]
    sha256 = "adb0dd5813acc88796dd74e181efaf71432e6fb526053c4a797c701e4bc0b5ef"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.0+0/utf8proc.v2.11.0.armv7l-linux-gnueabihf.tar.gz"
[[utf8proc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6e5e2aaecc11897c288162135b2c84e8e8c7b5f3"
libc = "musl"
os = "linux"

    [[utf8proc.download]]
    sha256 = "0c3bb1a20719e85a617755b957b0b5bb4ab73defe5b9c83cd714f6ecd0be26a6"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.0+0/utf8proc.v2.11.0.armv7l-linux-musleabihf.tar.gz"
[[utf8proc]]
arch = "i686"
git-tree-sha1 = "e54d0078e58618445e2feecfc0c2c1042719ba5d"
libc = "glibc"
os = "linux"

    [[utf8proc.download]]
    sha256 = "61dd83236aa387c0d4b379a8c6277a2f7d3fc49cfa35539b40eff4ee290ae798"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.0+0/utf8proc.v2.11.0.i686-linux-gnu.tar.gz"
[[utf8proc]]
arch = "i686"
git-tree-sha1 = "0e340779d3cfaebe21718cc1888c7aea502a7b0e"
libc = "musl"
os = "linux"

    [[utf8proc.download]]
    sha256 = "2dfc147ba8a1530b3daa964e59450febac00db5a2f917dc37a6925e3cd6d8104"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.0+0/utf8proc.v2.11.0.i686-linux-musl.tar.gz"
[[utf8proc]]
arch = "i686"
git-tree-sha1 = "e98d80765355a764b98d8d5876fa08038c1de03e"
os = "windows"

    [[utf8proc.download]]
    sha256 = "10264ca3997ddff416aa5138e5ce19976a3b6d463320c53e35847f0bdf638657"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.0+0/utf8proc.v2.11.0.i686-w64-mingw32.tar.gz"
[[utf8proc]]
arch = "powerpc64le"
git-tree-sha1 = "2991424a24c2fb0eba8585bc16a19a4c797f10a2"
libc = "glibc"
os = "linux"

    [[utf8proc.download]]
    sha256 = "8f8fb37c8d58105a6ae9d76878c3218110ea1b94f79a7a32b9110eec83fa67ed"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.0+0/utf8proc.v2.11.0.powerpc64le-linux-gnu.tar.gz"
[[utf8proc]]
arch = "riscv64"
git-tree-sha1 = "248530dede350e139bbbbaa196d5fbbc234db14d"
libc = "glibc"
os = "linux"

    [[utf8proc.download]]
    sha256 = "82c144da4b6f28db97d790ca18f5d622ddb2bd56814a35e8619078207ec03afa"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.0+0/utf8proc.v2.11.0.riscv64-linux-gnu.tar.gz"
[[utf8proc]]
arch = "x86_64"
git-tree-sha1 = "f913913ed53e21a5524329f63579f2ac9480bd6c"
os = "macos"

    [[utf8proc.download]]
    sha256 = "568c4b80c2f825050f8afd8a67b17c0db28d1576b51327e60777c989234cb533"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.0+0/utf8proc.v2.11.0.x86_64-apple-darwin.tar.gz"
[[utf8proc]]
arch = "x86_64"
git-tree-sha1 = "937f9b60fd36d62f588078c61c7deee703ff7c21"
libc = "glibc"
os = "linux"

    [[utf8proc.download]]
    sha256 = "f08346d555047dbf547ea7f60b375834c36bc4c32312090f5c2729961b7044cf"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.0+0/utf8proc.v2.11.0.x86_64-linux-gnu.tar.gz"
[[utf8proc]]
arch = "x86_64"
git-tree-sha1 = "26e7c66966b6d3b91663011c5cc9e8d00ec33507"
libc = "musl"
os = "linux"

    [[utf8proc.download]]
    sha256 = "70dde23524b66880d6c2e79aa0ccb6d249104b28ecbd200d1baf69808eecf545"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.0+0/utf8proc.v2.11.0.x86_64-linux-musl.tar.gz"
[[utf8proc]]
arch = "x86_64"
git-tree-sha1 = "273d9753a96df7343cab74999fe691e889b38e98"
os = "freebsd"

    [[utf8proc.download]]
    sha256 = "5fc9a98e2b33ecbd41b71d1bff98f430d37d3c48ed41d97450c4db4840c41f14"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.0+0/utf8proc.v2.11.0.x86_64-unknown-freebsd.tar.gz"
[[utf8proc]]
arch = "x86_64"
git-tree-sha1 = "50517e10f891314589ed202bba9db7a80449afdf"
os = "windows"

    [[utf8proc.download]]
    sha256 = "de402647c3d5103bab1d3c46d2c8d1b7a1ae69f8813ba7d2584cb2b6e83d7f5e"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.0+0/utf8proc.v2.11.0.x86_64-w64-mingw32.tar.gz"
