[[utf8proc]]
arch = "aarch64"
git-tree-sha1 = "78565bb9280148d7d4041b677c5361f905b9ee1a"
os = "macos"

    [[utf8proc.download]]
    sha256 = "ea7d0378a6c03616b1edcbf595a975a0cb96c1af153f8f06f65bb939d35c605f"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.3+0/utf8proc.v2.11.3.aarch64-apple-darwin.tar.gz"
[[utf8proc]]
arch = "aarch64"
git-tree-sha1 = "494696861a741c54d4cc4303787ab7e19c2966fa"
libc = "glibc"
os = "linux"

    [[utf8proc.download]]
    sha256 = "dc3ee9e3df25260c676985d3c7745454c9f18425c2b1a4813fea08725cf800d0"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.3+0/utf8proc.v2.11.3.aarch64-linux-gnu.tar.gz"
[[utf8proc]]
arch = "aarch64"
git-tree-sha1 = "f223bbe0980c05b92c45c386e96e0eb76c7e85ce"
libc = "musl"
os = "linux"

    [[utf8proc.download]]
    sha256 = "ad10e19b91db3c650028ed78a0141457cf1f2e2c7b5fb20d1aa35d8e9c9037fa"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.3+0/utf8proc.v2.11.3.aarch64-linux-musl.tar.gz"
[[utf8proc]]
arch = "aarch64"
git-tree-sha1 = "4f4cd9a2bd5b46719a5d659e8d8f3092899a53a5"
os = "freebsd"

    [[utf8proc.download]]
    sha256 = "f6c809e32adfbdcb6b806e6a9062b8be4c49cca1d58b02f2979bc3ddfb346841"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.3+0/utf8proc.v2.11.3.aarch64-unknown-freebsd.tar.gz"
[[utf8proc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4a32677b807aa74aa4e36797c8cb431de5d11bf1"
libc = "glibc"
os = "linux"

    [[utf8proc.download]]
    sha256 = "cc635b87713db79b6ec94f50eb0ab6454111258bc6864b7fcd761a9f3a76ce59"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.3+0/utf8proc.v2.11.3.armv6l-linux-gnueabihf.tar.gz"
[[utf8proc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c81db5cae4c5812063cd337ff88069d37e3eab9c"
libc = "musl"
os = "linux"

    [[utf8proc.download]]
    sha256 = "0f769758d9ecfa3168ae4149b9382559b3e021a9ac9b5c242d58d270e6332b1b"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.3+0/utf8proc.v2.11.3.armv6l-linux-musleabihf.tar.gz"
[[utf8proc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4053919cc5c6dd3287faf139a349b774cf2e9995"
libc = "glibc"
os = "linux"

    [[utf8proc.download]]
    sha256 = "3e5df9871314b27747efdfd8ac2f8a014a1cca3af4125cc02ae7aa0c552ca819"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.3+0/utf8proc.v2.11.3.armv7l-linux-gnueabihf.tar.gz"
[[utf8proc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0fa68455e37dee85cd52b061198f04ab8c396652"
libc = "musl"
os = "linux"

    [[utf8proc.download]]
    sha256 = "e2ccf2e7e8a712c15c9607180a0d26f6ff49b74d244571d152de719ea2c41bcf"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.3+0/utf8proc.v2.11.3.armv7l-linux-musleabihf.tar.gz"
[[utf8proc]]
arch = "i686"
git-tree-sha1 = "a332e2766a27a6f8dfbc188955a652f911cb0dcc"
libc = "glibc"
os = "linux"

    [[utf8proc.download]]
    sha256 = "7ea597ad447693bee166abdacc58998054fdbfafd09bb34527644dad32e4b78b"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.3+0/utf8proc.v2.11.3.i686-linux-gnu.tar.gz"
[[utf8proc]]
arch = "i686"
git-tree-sha1 = "2175dc3a9d69155bba77db8f313cfe198cb18ace"
libc = "musl"
os = "linux"

    [[utf8proc.download]]
    sha256 = "6ce95a52c13a3a83a9d77bb5734d522685df533433a1d0c9477877dacbc88906"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.3+0/utf8proc.v2.11.3.i686-linux-musl.tar.gz"
[[utf8proc]]
arch = "i686"
git-tree-sha1 = "8203f57b40fc4a73e3775a98fd29c7b334c9868b"
os = "windows"

    [[utf8proc.download]]
    sha256 = "6bba42e6622ff4022861b9bc2dfa0030363dc8e627293aca4bef45e736d9a1ea"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.3+0/utf8proc.v2.11.3.i686-w64-mingw32.tar.gz"
[[utf8proc]]
arch = "powerpc64le"
git-tree-sha1 = "392925ba2801de326c67ff202830d8cf98849a0d"
libc = "glibc"
os = "linux"

    [[utf8proc.download]]
    sha256 = "35c2bf65868644b34fb3a283c59cc40faaed7e7ebce839f9dd85dfc86c162ae3"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.3+0/utf8proc.v2.11.3.powerpc64le-linux-gnu.tar.gz"
[[utf8proc]]
arch = "riscv64"
git-tree-sha1 = "47381124dd097514c53c5f05ebc2e035b5107be5"
libc = "glibc"
os = "linux"

    [[utf8proc.download]]
    sha256 = "d83d39461ac2efecf0c4d3235836401206fa63b5753f49cec744f3b1cfd02db9"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.3+0/utf8proc.v2.11.3.riscv64-linux-gnu.tar.gz"
[[utf8proc]]
arch = "x86_64"
git-tree-sha1 = "4a3cd92e8932757cea4265ef324df0bb86b1312e"
os = "macos"

    [[utf8proc.download]]
    sha256 = "70b6a20644b72c563f05033c51c1bf54a1502743f149363fc2099a70bac943a5"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.3+0/utf8proc.v2.11.3.x86_64-apple-darwin.tar.gz"
[[utf8proc]]
arch = "x86_64"
git-tree-sha1 = "56b65680930268d6fac9b61bf80533f4db4579d6"
libc = "glibc"
os = "linux"

    [[utf8proc.download]]
    sha256 = "fc77f035b3bb8ac954876815a296a4bd9d5b0fd27d17c02bdddcc7a778fe88cd"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.3+0/utf8proc.v2.11.3.x86_64-linux-gnu.tar.gz"
[[utf8proc]]
arch = "x86_64"
git-tree-sha1 = "55e7465199b31c241cf2b5b4a5e41f2f159451b5"
libc = "musl"
os = "linux"

    [[utf8proc.download]]
    sha256 = "c3116a7e973795c5048565483a805ac9edf7b433ef0a5df7abdfbd903a5b9f77"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.3+0/utf8proc.v2.11.3.x86_64-linux-musl.tar.gz"
[[utf8proc]]
arch = "x86_64"
git-tree-sha1 = "265b7dacf367898e9b03527ea1858da4c7648ac3"
os = "freebsd"

    [[utf8proc.download]]
    sha256 = "4416a2a25154eac728cbdb71c09c56174ff0cb28c35b82c75eb053b5a93f0d91"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.3+0/utf8proc.v2.11.3.x86_64-unknown-freebsd.tar.gz"
[[utf8proc]]
arch = "x86_64"
git-tree-sha1 = "92705e463f652cc74737dcb0f0e8b295b51f1586"
os = "windows"

    [[utf8proc.download]]
    sha256 = "4e936eede11ced1f786b2375efa19888becc064092df318da8f79704b24fb406"
    url = "https://github.com/JuliaBinaryWrappers/utf8proc_jll.jl/releases/download/utf8proc-v2.11.3+0/utf8proc.v2.11.3.x86_64-w64-mingw32.tar.gz"
